In [1]:
import numpy as np

In [11]:
adj = np.array([[0, 1, 1, 1, 1, 0, 0, 0, 0, 1.],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0.],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0.],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0.],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0.],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1.],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1.],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1.],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1.],
 [1, 0, 0, 0, 0, 1, 1, 1, 1, 0.]])

action = np.array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [18]:
action = action.reshape(10, 1)


In [19]:
act_tiled = np.tile(action, (1, 10))
act_tiled

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
tx_to_where = np.multiply(adj, act_tiled)
tx_to_where

array([[0., 1., 1., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
for i in np.where(action == 1)[0]:
    tx_to_where[:, i] = 0

collided_index = np.sum(tx_to_where, axis=0)>1
collided_index

tx_to_where[:, collided_index] = 0
tx_to_where


array([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.where(tx_to_where.sum(axis=1)==0)

(array([1, 2, 3, 4, 6, 7, 8, 9]),)

In [29]:
np.count_nonzero(tx_to_where.sum(axis=1))

2

In [5]:
def calc(x):
    return x+1, x*10

a, b = calc(3)
a_cum, b_cum = zip(*[calc(i) for i in range(10)])
a_cum, b_cum

((1, 2, 3, 4, 5, 6, 7, 8, 9, 10), (0, 10, 20, 30, 40, 50, 60, 70, 80, 90))