In [1]:
import pandas as pd
import numpy as np


In [4]:
adjacency_matrix = np.zeros((10, 10))

In [5]:
adjacency_matrix[:] = 1
adjacency_matrix = [[0 if i == j else 1 for j in range(10)] for i in range(10)]
print(adjacency_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:

AGECOEFF = 1
n_steps = 300
n_nodes = 10
tx_prob = 1/n_nodes
data_tx = np.zeros((n_steps, n_nodes))
data_aoi = np.zeros((n_steps, n_nodes))
data_done_within_epi = np.zeros(n_nodes)
reward = np.zeros((n_steps, 1))

for i in range(1, n_steps):
    data_tx[i] = (np.random.rand(n_nodes)<tx_prob).astype(int)
    # Success if only one node transmits
    if np.sum(data_tx[i]) == 1:
        succ_idx = np.where(data_tx[i])[0]
        for j in range(n_nodes):
            if j == succ_idx:
                data_aoi[i,j] = 0
                data_done_within_epi[j] = 1
            else:
                data_aoi[i,j] = data_aoi[i-1,j] + (1/n_steps)
    else:
        succ_idx = []
        data_aoi[i,:] = data_aoi[i-1,:] + (1/n_steps)
    reward[i] = len(succ_idx)


sum(reward)

In [3]:
a = True
print(f"{a}")

True


In [6]:
import torch
a = torch.zeros(size=(10, 100))
print(a.shape)

torch.Size([10, 100])


In [7]:
b = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[:, 0] = b
print(a)

tensor([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.],
        [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.

In [21]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [22]:
Q = 2*a**3 - b**2
print(Q)

tensor([-20.,  38.], grad_fn=<SubBackward0>)


In [23]:
Q.sum().backward()

In [25]:
print(a.grad, b.grad)

tensor([24., 54.]) tensor([-12.,  -8.])


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
a, b, *c = arr
print(a, b, c)

1 2 [3, 4, 5]
